<script src="{{ asset('admin/assets/lib/jquery/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/js/app.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/jquery.flot.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/jquery.flot.pie.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/jquery.flot.time.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/jquery.flot.resize.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/plugins/jquery.flot.orderBars.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/plugins/curvedLines.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/plugins/jquery.flot.tooltip.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery.sparkline/jquery.sparkline.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/countup/countUp.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-ui/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jqvmap/jquery.vmap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jqvmap/maps/jquery.vmap.world.js') }}" type="text/javascript"></script>

<script src="{{ asset('admin/assets/lib/summernote/summernote-bs4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/summernote/summernote-ext-beagle.js') }}" type="text/javascript"></script>